#!/usr/bin/env python3
"""
OSE Weaver Protocol v2.0 - PLATINUM Format
Auto-generates comprehensive build instructions from CAD JSON data.

Features:
- Tools list
- Lumber cut list  
- Hardware estimates (screws, nails)
- Logical assembly phases
- ASCII diagrams
- Time and cost estimates
"""

import json
import sys
import os
import math
import re
from datetime import datetime
from collections import defaultdict

# ============================================================================
# Configuration
# ============================================================================

# Standard hardware estimates per connection type
HARDWARE_ESTIMATES = {
    "joist_to_rim": 3,      # 3 screws per joist-to-rim connection
    "sheathing_edge": 6,    # screws per 8' edge
    "sheathing_field": 12,  # screws per 4x8 sheet field
    "insulation": 0,        # friction fit, no fasteners
}

# Standard tool list for floor modules
STANDARD_TOOLS = [
    ("Circular Saw", "Cutting lumber to length"),
    ("Drill/Driver", "Driving screws"),
    ("Framing Square", "Ensuring 90° corners"),
    ("Tape Measure", "Measuring / layout"),
    ("Chalk Line", "Marking joist positions"),
    ("Level (4')", "Checking for level/flat"),
    ("Speed Square", "Marking cut lines"),
    ("Hammer", "Adjustments, persuasion"),
    ("Safety Glasses", "Eye protection"),
    ("Work Gloves", "Hand protection"),
]

# Lumber dimension patterns (regex)
LUMBER_PATTERNS = {
    r"2x4": {"width": 1.5, "height": 3.5, "name": "2x4"},
    r"2x6": {"width": 1.5, "height": 5.5, "name": "2x6"},
    r"2x8": {"width": 1.5, "height": 7.25, "name": "2x8"},
    r"2x10": {"width": 1.5, "height": 9.25, "name": "2x10"},
    r"2x12": {"width": 1.5, "height": 11.25, "name": "2x12"},
}

# ============================================================================
# Helper Functions
# ============================================================================

def parse_placement(placement_str):
    """Parse FreeCAD Placement string to get position."""
    try:
        pos_part = placement_str.split("Pos=(")[1].split(")")[0]
        x, y, z = map(float, pos_part.split(","))
        return x, y, z
    except:
        return 0.0, 0.0, 0.0


def mm_to_inches(mm):
    """Convert millimeters to inches."""
    return mm / 25.4


def mm_to_feet(mm):
    """Convert millimeters to feet."""
    return mm / 304.8


def classify_part(label):
    """Classify a part by its label into categories."""
    label_lower = label.lower()
    
    if "joist" in label_lower and "rim" in label_lower:
        return "rim_joist"
    elif "joist" in label_lower:
        return "floor_joist"
    elif "osb" in label_lower:
        return "osb_sheathing"
    elif "plywood" in label_lower:
        return "plywood_sheathing"
    elif "insulation" in label_lower:
        return "insulation"
    elif "water inlet" in label_lower or "inlet" in label_lower:
        return "water_inlet"
    elif "2x4" in label_lower:
        return "framing_2x4"
    elif "2x8" in label_lower:
        return "framing_2x8"
    else:
        return "other"


def get_lumber_size(label):
    """Extract lumber size from label (e.g., '2x8' from '2x8 Joist 001')."""
    for pattern, info in LUMBER_PATTERNS.items():
        if re.search(pattern, label, re.IGNORECASE):
            return info["name"]
    return None


def estimate_module_dimensions(parts):
    """Estimate overall module dimensions from part positions."""
    max_x, max_y, max_z = 0, 0, 0
    
    for p in parts:
        if "properties" in p and "Placement" in p["properties"]:
            x, y, z = parse_placement(p["properties"]["Placement"])
            max_x = max(max_x, abs(x))
            max_y = max(max_y, abs(y))
            max_z = max(max_z, abs(z))
    
    # Convert to feet (rough estimate)
    width_ft = max(6, round(mm_to_feet(max_x + 2000)))  # Add buffer
    length_ft = max(8, round(mm_to_feet(max_y + 2000)))
    depth_in = max(8, round(mm_to_inches(max_z + 200)))
    
    return width_ft, length_ft, depth_in


# ============================================================================
# Main Generation Functions
# ============================================================================

def generate_overview(filename, parts, width_ft, length_ft, depth_in):
    """Generate the overview section."""
    lines = []
    lines.append(f"# {filename.replace('.fcstd', '').replace('.json', '')} - Build Instructions")
    lines.append(f"> **OSE Seed Home | {width_ft}' x {length_ft}' Floor Module**")
    lines.append(f"> Auto-generated by OSE Weaver Protocol v2.0 (Platinum Format)")
    lines.append(f"> Date: {datetime.now().strftime('%B %d, %Y')}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 📋 Overview")
    lines.append("")
    lines.append(f"**Dimensions**: {width_ft}' wide × {length_ft}' long × ~{depth_in}\" deep")
    lines.append(f"**Assembly Time**: ~{max(2, (width_ft * length_ft) // 30)}-{max(4, (width_ft * length_ft) // 20)} hours (2 people)")
    lines.append("**Skill Level**: Intermediate (framing experience helpful)")
    lines.append("")
    return lines


def generate_tools_section():
    """Generate the tools required section."""
    lines = []
    lines.append("---")
    lines.append("")
    lines.append("## 🔧 Tools Required")
    lines.append("")
    lines.append("| Tool | Purpose |")
    lines.append("|------|---------|")
    for tool, purpose in STANDARD_TOOLS:
        lines.append(f"| {tool} | {purpose} |")
    lines.append("")
    return lines


def generate_lumber_section(parts):
    """Generate lumber cut list from parts."""
    lines = []
    lines.append("---")
    lines.append("")
    lines.append("## 🪵 Lumber Cut List")
    lines.append("")
    
    # Categorize lumber
    lumber_counts = defaultdict(lambda: defaultdict(int))
    
    for p in parts:
        label = p.get("label", "")
        category = classify_part(label)
        lumber_size = get_lumber_size(label)
        
        if lumber_size and category in ["rim_joist", "floor_joist", "framing_2x4", "framing_2x8"]:
            lumber_counts[lumber_size][category] += 1
    
    # Frame lumber
    if lumber_counts:
        lines.append("### Frame Lumber")
        lines.append("| Part | Qty | Size | Notes |")
        lines.append("|------|-----|------|-------|")
        
        for size, categories in lumber_counts.items():
            for cat, count in categories.items():
                cat_name = cat.replace("_", " ").title()
                lines.append(f"| {cat_name} ({size}) | {count} | See CAD | From extracted data |")
    
    lines.append("")
    return lines


def generate_sheet_goods_section(parts):
    """Generate sheet goods section."""
    lines = []
    lines.append("---")
    lines.append("")
    lines.append("## 📦 Sheet Goods")
    lines.append("")
    
    osb_count = sum(1 for p in parts if "osb" in p.get("label", "").lower() and p.get("type_id") in ["Part::Box", "Part::Feature"])
    plywood_count = sum(1 for p in parts if "plywood" in p.get("label", "").lower() and p.get("type_id") in ["Part::Box", "Part::Feature"])
    
    if plywood_count > 0:
        lines.append("### Bottom Sheathing (3/4\" Pressure Treated Plywood)")
        lines.append("| Part | Qty | Size | Notes |")
        lines.append("|------|-----|------|-------|")
        lines.append(f"| PT Plywood | {plywood_count} | 4' × 8' | Bottom layer - moisture barrier |")
        lines.append("")
    
    if osb_count > 0:
        lines.append("### Top Sheathing (3/4\" OSB)")
        lines.append("| Part | Qty | Size | Notes |")
        lines.append("|------|-----|------|-------|")
        lines.append(f"| OSB | {osb_count} | 4' × 8' | Top subfloor surface |")
        lines.append("")
    
    return lines


def generate_insulation_section(parts):
    """Generate insulation section."""
    lines = []
    insulation_count = sum(1 for p in parts if "insulation" in p.get("label", "").lower() and p.get("type_id") == "Part::Box")
    
    if insulation_count > 0:
        lines.append("---")
        lines.append("")
        lines.append("## 🧊 Insulation")
        lines.append("")
        lines.append("| Part | Qty | Size | Notes |")
        lines.append("|------|-----|------|-------|")
        lines.append(f"| R-30 Batt Insulation | {insulation_count} | 16\" × 93\" | Between joists |")
        lines.append("| *Install after frame complete, before top sheathing*")
        lines.append("")
    
    return lines


def generate_hardware_section(parts):
    """Generate hardware estimates."""
    lines = []
    lines.append("---")
    lines.append("")
    lines.append("## 🔩 Hardware")
    lines.append("")
    
    # Count parts to estimate hardware
    joist_count = sum(1 for p in parts if "joist" in p.get("label", "").lower() and "rim" not in p.get("label", "").lower())
    sheet_count = sum(1 for p in parts if any(x in p.get("label", "").lower() for x in ["osb", "plywood"]) and p.get("type_id") in ["Part::Box", "Part::Feature"])
    
    deck_screws_3in = joist_count * HARDWARE_ESTIMATES["joist_to_rim"]
    deck_screws_2in = sheet_count * HARDWARE_ESTIMATES["sheathing_edge"]
    subfloor_screws = sheet_count * (HARDWARE_ESTIMATES["sheathing_edge"] + HARDWARE_ESTIMATES["sheathing_field"])
    
    lines.append("### Screws (Recommended)")
    lines.append("| Type | Qty | Purpose |")
    lines.append("|------|-----|---------|")
    lines.append(f"| 3\" Deck Screws | ~{max(50, deck_screws_3in)} | Joist-to-joist connections |")
    lines.append(f"| 2\" Deck Screws | ~{max(100, deck_screws_2in)} | Sheathing to joists |")
    lines.append(f"| 1-5/8\" Subfloor Screws | ~{max(100, subfloor_screws)} | OSB to joists |")
    lines.append("")
    
    lines.append("### Optional/Recommended")
    lines.append("| Item | Qty | Purpose |")
    lines.append("|------|-----|---------|")
    lines.append("| Construction Adhesive | 2 tubes | Glue sheathing to joists (reduces squeaks) |")
    lines.append(f"| Joist Hangers (2x8) | {joist_count} | Code-compliant joist connections |")
    lines.append("| Simpson Strong-Ties | 4 | Corner reinforcement |")
    lines.append("")
    
    return lines


def generate_assembly_steps(parts, width_ft, length_ft):
    """Generate logical assembly phases."""
    lines = []
    lines.append("---")
    lines.append("")
    lines.append("## 🏗️ Assembly Steps")
    lines.append("")
    
    # Phase 1: Frame
    lines.append("### Phase 1: Build the Floor Frame (Ground Level)")
    lines.append("")
    lines.append("**Step 1: Layout Rim Joists**")
    lines.append(f"1. Place both {length_ft}' rim joists parallel on sawhorses or blocks")
    lines.append(f"2. Measure to ensure they are exactly {width_ft}' apart (outside to outside)")
    lines.append("3. Mark joist locations on rim joists at 16\" on-center")
    lines.append("")
    
    joist_count = sum(1 for p in parts if "joist" in p.get("label", "").lower() and "rim" not in p.get("label", "").lower())
    lines.append("**Step 2: Install Floor Joists**")
    lines.append("1. Position first floor joist flush with one end")
    lines.append("2. Drive 3 screws (or nails) through rim joist into joist end")
    lines.append(f"3. Repeat for all {joist_count} floor joists at marked locations")
    lines.append("4. Use framing square to ensure 90° at each connection")
    lines.append("")
    
    lines.append("**Step 3: Square the Frame**")
    lines.append("1. Measure diagonals (corner to corner)")
    lines.append("2. Adjust until diagonals are equal (±1/8\")")
    lines.append("3. Frame is now square")
    lines.append("")
    
    # Check for water inlet
    has_water_inlet = any("water" in p.get("label", "").lower() or "inlet" in p.get("label", "").lower() for p in parts)
    if has_water_inlet:
        lines.append("**Step 4: Install Water Inlet Frame**")
        lines.append("1. Locate water inlet position (near corner per CAD drawing)")
        lines.append("2. Install 2x4 and 2x8 blocking to create opening")
        lines.append("3. Opening should be sized for your specific water inlet pipe")
        lines.append("")
    
    lines.append("> ✅ **QC Checkpoint**: Frame should be square, level, and all joists secured.")
    lines.append("")
    
    # Phase 2: Bottom Sheathing
    plywood_count = sum(1 for p in parts if "plywood" in p.get("label", "").lower() and p.get("type_id") in ["Part::Box", "Part::Feature"])
    if plywood_count > 0:
        lines.append("---")
        lines.append("")
        lines.append("### Phase 2: Install Bottom Sheathing")
        lines.append("")
        lines.append("**Step 5: Install Plywood Sheathing**")
        lines.append("1. Start at one end with full 4'×8' sheet")
        lines.append("2. Apply construction adhesive to joist bottoms (optional but recommended)")
        lines.append("3. Position plywood flush with frame edges")
        lines.append("4. Drive 2\" screws every 6\" along edges, 12\" in field")
        lines.append("5. Stagger joints between rows")
        lines.append("6. Cut final sheet to fit")
        lines.append("")
        
        if has_water_inlet:
            lines.append("**Step 6: Cut Water Inlet Hole**")
            lines.append("1. Mark circular cutout position from inside")
            lines.append("2. Drill pilot hole at center")
            lines.append("3. Use jigsaw to cut circle (match pipe diameter + 1/4\")")
            lines.append("")
        
        lines.append("> ✅ **QC Checkpoint**: All sheathing edges supported by joists. No gaps > 1/8\".")
        lines.append("")
    
    # Phase 3: Insulation
    insulation_count = sum(1 for p in parts if "insulation" in p.get("label", "").lower())
    if insulation_count > 0:
        lines.append("---")
        lines.append("")
        lines.append("### Phase 3: Install Insulation")
        lines.append("")
        lines.append("**Step 7: Install Batt Insulation**")
        lines.append("1. Frame should now be right-side up")
        lines.append("2. Cut insulation batts to fit between joists")
        lines.append("3. Place batts paper-side UP (toward living space)")
        lines.append("4. Fill all joist bays completely")
        lines.append("5. Avoid compressing insulation - reduces R-value")
        lines.append("")
        lines.append("> ⚠️ **Important**: Do not leave gaps. Insulation should fit snugly but not be compressed.")
        lines.append("")
    
    # Phase 4: Top Sheathing
    osb_count = sum(1 for p in parts if "osb" in p.get("label", "").lower() and p.get("type_id") in ["Part::Box", "Part::Feature"])
    if osb_count > 0:
        lines.append("---")
        lines.append("")
        lines.append("### Phase 4: Install Top Sheathing (Subfloor)")
        lines.append("")
        lines.append("**Step 8: Install OSB Sheathing**")
        lines.append("1. Apply construction adhesive to joist tops")
        lines.append("2. Start at one end, flush with frame edges")
        lines.append("3. Drive 1-5/8\" subfloor screws every 6\" along edges, 8\" in field")
        lines.append("4. Stagger joints (offset from plywood layer below)")
        lines.append("5. Leave 1/8\" gap between sheets for expansion")
        lines.append("")
        
        if has_water_inlet:
            lines.append("**Step 9: Cut Water Inlet Hole**")
            lines.append("1. Transfer hole position from below")
            lines.append("2. Cut matching circular opening in OSB")
            lines.append("")
        
        lines.append("> ✅ **QC Checkpoint**: Walk entire surface. No squeaks or soft spots.")
        lines.append("")
    
    # Phase 5: Final QC
    lines.append("---")
    lines.append("")
    lines.append("### Phase 5: Final QC & Completion")
    lines.append("")
    lines.append("**Final Inspection Checklist:**")
    lines.append("- [ ] All screws/nails driven flush")
    lines.append("- [ ] No gaps in insulation")
    lines.append("- [ ] Subfloor is flat and level")
    if has_water_inlet:
        lines.append("- [ ] Water inlet opening aligned top-to-bottom")
    lines.append("- [ ] Edges clean and square")
    lines.append("- [ ] Module ready for transport or installation")
    lines.append("")
    
    return lines


def generate_diagrams(width_ft, length_ft):
    """Generate ASCII reference diagrams."""
    lines = []
    lines.append("---")
    lines.append("")
    lines.append("## 📐 Reference Diagrams")
    lines.append("")
    lines.append("### Joist Layout (Top View)")
    lines.append("```")
    lines.append(f"┌{'─' * 70}┐")
    lines.append(f"│  RIM JOIST ({length_ft}'){' ' * (68 - len(str(length_ft)) - 15)}│")
    lines.append(f"├────┬────┬────┬────┬────┬{'─' * 40}┬──────┤")
    lines.append(f"│    │    │    │    │    │{' ' * 40}│ ○    │")
    lines.append(f"│    │    │    │    │    │{' ' * 40}│water │")
    lines.append(f"│    │    │    │    │    │{' ' * 40}│inlet │")
    lines.append(f"├────┴────┴────┴────┴────┴{'─' * 40}┴──────┤")
    lines.append(f"│  RIM JOIST ({length_ft}'){' ' * (68 - len(str(length_ft)) - 15)}│")
    lines.append(f"└{'─' * 70}┘")
    lines.append("     ↑    ↑    ↑    ↑    ↑")
    lines.append("   Joists @ 16\" OC")
    lines.append("```")
    lines.append("")
    
    lines.append("### Cross-Section")
    lines.append("```")
    lines.append("        ┌────────────────────────────────────┐")
    lines.append("        │      OSB (3/4\")                    │  ← Subfloor")
    lines.append("        ├────┬─────────────────┬─────────────┤")
    lines.append("        │2x8 │  INSULATION     │ 2x8        │  ← Joists + Batt")
    lines.append("        │    │  R-30 BATT      │            │")
    lines.append("        ├────┴─────────────────┴─────────────┤")
    lines.append("        │      PT PLYWOOD (3/4\")             │  ← Moisture Barrier")
    lines.append("        └────────────────────────────────────┘")
    lines.append("```")
    lines.append("")
    
    return lines


def generate_time_cost(width_ft, length_ft, parts):
    """Generate time and cost estimates."""
    lines = []
    
    # Time estimates
    lines.append("---")
    lines.append("")
    lines.append("## ⏱️ Time Estimates")
    lines.append("")
    lines.append("| Phase | Time (2 people) |")
    lines.append("|-------|-----------------|")
    lines.append("| 1. Frame Assembly | 1 hour |")
    lines.append("| 2. Bottom Sheathing | 1 hour |")
    lines.append("| 3. Insulation | 30 min |")
    lines.append("| 4. Top Sheathing | 1 hour |")
    lines.append("| 5. QC & Cleanup | 30 min |")
    lines.append("| **Total** | **4 hours** |")
    lines.append("")
    
    # Cost estimates (rough)
    sq_ft = width_ft * length_ft
    lumber_cost = int(sq_ft * 1.5)
    plywood_cost = int(sq_ft * 2.5)
    osb_cost = int(sq_ft * 1.25)
    insulation_cost = int(sq_ft * 0.75)
    hardware_cost = 50
    total = lumber_cost + plywood_cost + osb_cost + insulation_cost + hardware_cost
    
    lines.append("---")
    lines.append("")
    lines.append("## 💰 Estimated Cost")
    lines.append("")
    lines.append("| Category | Cost |")
    lines.append("|----------|------|")
    lines.append(f"| Lumber | ~${lumber_cost} |")
    lines.append(f"| PT Plywood | ~${plywood_cost} |")
    lines.append(f"| OSB | ~${osb_cost} |")
    lines.append(f"| Insulation | ~${insulation_cost} |")
    lines.append(f"| Hardware | ~${hardware_cost} |")
    lines.append(f"| **Total** | **~${total}** |")
    lines.append("")
    lines.append("*Prices vary by region and market conditions.*")
    lines.append("")
    
    return lines


def generate_footer(filename):
    """Generate footer section."""
    lines = []
    lines.append("---")
    lines.append("")
    lines.append("## 📝 Notes")
    lines.append("")
    lines.append("- This module is part of a multi-module floor system")
    lines.append("- Ensure proper vapor barrier on bottom (PT plywood serves this purpose)")
    lines.append("- Module designed to connect to other OSE modules")
    lines.append("- See OSE Wiki for full Seed Home documentation")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("> **Generated by**: OSE Weaver Protocol v2.0 (Platinum Format)")
    lines.append(f"> **Source File**: {filename}")
    lines.append("> **Agent**: Antigravity (Gemini)")
    lines.append("")
    
    return lines


# ============================================================================
# Main Entry Point
# ============================================================================

def weave_platinum_instructions(json_path, output_path=None):
    """Generate platinum-quality build instructions from CAD JSON."""
    
    # Load data
    with open(json_path, 'r') as f:
        data = json.load(f)
    
    filename = data.get("filename", os.path.basename(json_path))
    parts = data.get("parts", [])
    
    # Filter to actual parts (not groups)
    real_parts = [p for p in parts if p.get("type_id") not in ["App::DocumentObjectGroup"]]
    
    # Estimate dimensions
    width_ft, length_ft, depth_in = estimate_module_dimensions(parts)
    
    # Generate all sections
    md_lines = []
    md_lines.extend(generate_overview(filename, parts, width_ft, length_ft, depth_in))
    md_lines.extend(generate_tools_section())
    md_lines.extend(generate_lumber_section(parts))
    md_lines.extend(generate_sheet_goods_section(parts))
    md_lines.extend(generate_insulation_section(parts))
    md_lines.extend(generate_hardware_section(parts))
    md_lines.extend(generate_assembly_steps(parts, width_ft, length_ft))
    md_lines.extend(generate_diagrams(width_ft, length_ft))
    md_lines.extend(generate_time_cost(width_ft, length_ft, parts))
    md_lines.extend(generate_footer(filename))
    
    # Write output
    if output_path is None:
        output_path = json_path.replace(".json", "_Instructions.md")
    
    with open(output_path, 'w') as f:
        f.write("\n".join(md_lines))
    
    print(f"✅ SUCCESS: Generated PLATINUM instructions at {output_path}")
    print(f"   - Parts analyzed: {len(parts)}")
    print(f"   - Real parts: {len(real_parts)}")
    print(f"   - Estimated size: {width_ft}' x {length_ft}'")
    
    return output_path


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: weave_instructions.py <input_json> [output_md]")
        print("  Generates PLATINUM quality build instructions from CAD JSON")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None
    
    weave_platinum_instructions(input_file, output_file)
